### ISSUE TITLE
”conda-lock install --name svi-state-estimation conda-lock.yml“ report error

### ISSUE THREAD

**Issue by fangkaiqi** [coursekevin/svise#2]
Traceback (most recent call last):
  File "/home/fangkaiqi/anaconda3/bin/conda-lock", line 8, in &lt;module&gt;
    sys.exit(main())
             ^^^^^^
  File "/home/fangkaiqi/anaconda3/lib/python3.11/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fangkaiqi/anaconda3/lib/python3.11/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/fangkaiqi/anaconda3/lib/python3.11/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fangkaiqi/anaconda3/lib/python3.11/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fangkaiqi/anaconda3/lib/python3.11/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
"/home/fangkaiqi/anaconda3/lib/python3.11/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fangkaiqi/anaconda3/lib/python3.11/site-packages/conda_lock/conda_lock.py", line 1486, in install
    with _render_lockfile_for_install(
  File "/home/fangkaiqi/anaconda3/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/home/fangkaiqi/anaconda3/lib/python3.11/site-packages/conda_lock/conda_lock.py", line 973, in _render_lockfile_for_install
    lock_content = parse_conda_lock_file(pathlib.Path(filename))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/fangkaiqi/anaconda3/lib/python3.11/site-packages/conda_lock/lockfile/__init__.py", line 145, in parse_conda_lock_file
    return lockfile_v1_to_v2(LockfileV1.parse_obj(content))
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "pydantic/main.py", line 526, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for Lockfile
package -&gt; 246 -&gt; optional
  field required (type=value_error.missing)

**Comment by coursekevin** [comment]
This looks like a conda / conda-lock issue. If you don't care about installing the same torch / cuda versions you can try skipping the conda steps.

In other words, after cloning the repo, just run:

`poetry install --with dev`

**Comment by coursekevin** [comment]
closing because of inactivity
